baseURL = "https://meja-kursi.bangunan.co/"
languageCode = "id"
title = "Meja dan Kursi Besi | Jual Meja dan Kursi Besi Minimalis Berbagai Model"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Custom Meja dan Kursi Besi Minimalis - Jual berbagai model meja dan kursi besi custom berkualitas dengan harga bersaing"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual meja besi", "kursi besi", "meja minimalis", "kursi minimalis", "furniture besi", "custom meja besi", "custom kursi besi", "meja besi murah"]
  base_price = 500000
  price_range = 200000
  free_shipping = true
  materials = [
  "Meja Besi Minimalis",
  "Kursi Besi Custom",
  "Meja Besi Kombinasi Kayu",
  "Kursi Besi Kombinasi Kayu",
  "Meja Besi Outdoor",
  "Kursi Besi Outdoor"
  ]
  categories = ["Meja Besi", "Kursi Besi", "Furniture Besi", "Furniture Minimalis"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Barang bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Penggantian atau pengembalian gratis untuk barang dengan cacat produksi.",
  "Barang yang tidak sesuai pesanan dapat dikembalikan tanpa biaya tambahan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Custom Meja dan Kursi Besi Berkualitas"
  hero_description = "Kami menawarkan berbagai model meja dan kursi besi minimalis berkualitas tinggi. Cocok untuk berbagai kebutuhan dengan custom desain yang modern dan bahan yang tahan lama."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Meja & Kursi"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan meja dan kursi besi minimalis berkualitas tinggi dengan berbagai pilihan desain, harga bersaing, dan layanan pengiriman free ongkir. Gratis konsultasi untuk membantu Anda memilih produk yang tepat untuk kebutuhan Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "meja-kursi.bangunan.co menawarkan berbagai model meja dan kursi besi berkualitas tinggi. Kami mengutamakan kepuasan pelanggan dengan produk yang tahan lama, estetis, dan harga yang bersaing. Pilih kami untuk melengkapi ruang Anda dengan furnitur besi minimalis terbaik."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Deni|Rudi|Hendra|Agus|Wawan|Rio}"
  message = "{Saya membeli meja dan kursi besi minimalis dari meja-kursi.bangunan.co untuk {rumah|proyek|ruang tamu|cafe} saya, dan hasilnya {sangat memuaskan|luar biasa|menakjubkan}. {Desainnya|Bentuknya} {modern|estetis|minimalis}, {kokoh|kuat|tahan lama}, dan sangat sesuai dengan {harapan|ekspektasi|keinginan} saya.|Produk meja dan kursi besi dari meja-kursi.bangunan.co {berkualitas|kokoh|estetis} dan sesuai dengan {ekspektasi|standar|harapan} saya.}"
  response = "{Terima kasih atas {kepercayaannya|pilihan Anda}! Kami senang Anda puas dengan meja dan kursi besi dari kami.|Kami sangat {menghargai|berterima kasih atas} kepercayaan Anda. Terima kasih sudah memilih produk kami.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Lina|Fitri|Diah|Nur|Maya}"
  message = "{meja-kursi.bangunan.co sangat {membantu|mempermudah} saya dalam membuat meja dan kursi besi yang cocok untuk {ruang tamu|proyek|rumah} saya. Hasilnya {sangat memuaskan|memenuhi harapan|luar biasa} dan sesuai dengan {keinginan|ekspektasi|rencana} saya.|Saya {sangat puas|terkesan|senang} dengan bantuan meja-kursi.bangunan.co untuk memilih furnitur besi yang tepat.}"
  response = "{Kami sangat {menghargai|berterima kasih atas} ulasan Anda. Senang mendengar bahwa Anda puas dengan {produk|furnitur} dan {layanan|pelayanan} dari kami.|Terima kasih banyak atas ulasannya, kami sangat senang mendengar kepuasan Anda.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Faisal|Galih|Rizal|Bambang|Ali|Fajar|Toni}"
  message = "{Meja dan kursi besi dari meja-kursi.bangunan.co {sangat estetis|modern|minimalis} dan {kokoh|tahan lama|berkualitas}. {Sangat cocok|Ideal} untuk proyek {cafe|perumahan|interior} saya, dan pengirimannya juga {cepat|aman|terjamin}.|Saya {puas|senang|terkesan} dengan meja dan kursi besi dari meja-kursi.bangunan.co. Produk ini sangat {kokoh|modern|estetis} dan pengirimannya {tepat|aman|cepat} sekali.}"
  response = "{Terima kasih! Kami {berkomitmen|berdedikasi|berfokus} untuk menyediakan meja dan kursi besi berkualitas dengan {layanan terbaik|pelayanan prima}.|Kami sangat senang mendengar bahwa Anda puas dengan produk kami.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Toni|Hendra|Dedi|Gilang|Ari|Wawan|Gani|Yudi}"
  message = "{Saya {sangat puas|terkesan|senang} dengan produk meja dan kursi besi dari meja-kursi.bangunan.co. {Kualitasnya|Mutunya} {sangat baik|terbaik|premium}, dan proses pengirimannya juga {cepat|tepat|terjamin} untuk proyek saya.|Produk meja dan kursi besi dari meja-kursi.bangunan.co {memenuhi ekspektasi|sangat baik|berkualitas}, dan pengirimannya juga {cepat|terjamin|efisien} untuk proyek saya.}"
  response = "{Senang mendengar Anda puas dengan produk kami. Terima kasih atas {kepercayaannya|pilihannya}!|Kami sangat menghargai kepercayaan Anda. Terima kasih sudah memilih produk kami.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan meja-kursi.bangunan.co {sangat memuaskan|luar biasa|terbaik}. Meja dan kursi besi yang saya {pesan|beli|pilih} {sangat berkualitas|berkualitas tinggi|bermutu} dan sesuai dengan {harapan|ekspektasi|rencana} saya.|Saya {senang|terkesan|puas} dengan pelayanan dari meja-kursi.bangunan.co. Produk meja dan kursinya {berkualitas|kokoh|modern} dan sesuai dengan keinginan saya.}"
  response = "{Terima kasih! Kami senang dapat {membantu|melayani} Anda melengkapi {rumah|proyek|ruangan} dengan furnitur besi minimalis terbaik.|Kami sangat menghargai ulasan Anda. Terima kasih telah memilih produk kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Deni|Rizal|Rio|Benny|Yanto|Galih|Toni|Faisal|Wawan}"
  message = "{Meja dan kursi besi dari meja-kursi.bangunan.co sangat {sesuai|tepat|cocok} dengan kebutuhan {cafe|proyek|ruang tamu|renovasi} saya. Proses pengirimannya {cepat|aman|terjamin} dan {efisien|tepat|teratur}.|Saya {puas|terkesan|senang} dengan produk meja dan kursi besi dari meja-kursi.bangunan.co. Furniturnya {berkualitas|kokoh|modern} dan pengirimannya {terjamin|cepat|aman}.}"
  response = "{Kami {senang|gembira} mendengar bahwa Anda puas dengan produk kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah {memilih|mempercayai} produk kami. Kami senang Anda puas dengan hasilnya.}"
  rating = 5

[[params.tabelItems]]
  name = "Meja Besi Minimalis"
  price = "1.500.000 /unit"
[[params.tabelItems]]
  name = "Kursi Besi Custom"
  price = "750.000 /unit"
[[params.tabelItems]]
  name = "Meja Besi Kombinasi Kayu"
  price = "2.000.000 /unit"
[[params.tabelItems]]
  name = "Kursi Besi Kombinasi Kayu"
  price = "1.000.000 /unit"
[[params.tabelItems]]
  name = "Meja Besi Outdoor"
  price = "1.800.000 /unit"
[[params.tabelItems]]
  name = "Kursi Besi Outdoor"
  price = "900.000 /unit"

[params.appliList]
  "Meja Besi Minimalis" = "interior rumah, ruang kerja"
  "Kursi Besi Custom" = "ruang tamu, ruang makan"
  "Meja Besi Kombinasi Kayu" = "dapur, ruang makan"
  "Kursi Besi Kombinasi Kayu" = "ruang makan, ruang tamu"
  "Meja Besi Outdoor" = "teras, taman"
  "Kursi Besi Outdoor" = "taman, area outdoor"

[params.kegunaanList]
  "Meja Besi Minimalis" = "cocok untuk interior minimalis di rumah atau ruang kerja"
  "Kursi Besi Custom" = "digunakan untuk ruang makan atau ruang tamu dengan desain minimalis"
  "Meja Besi Kombinasi Kayu" = "cocok untuk ruang makan atau dapur dengan kesan modern"
  "Kursi Besi Kombinasi Kayu" = "digunakan untuk melengkapi ruang makan atau ruang tamu"
  "Meja Besi Outdoor" = "digunakan untuk area outdoor seperti teras atau taman"
  "Kursi Besi Outdoor" = "cocok untuk taman atau ruang terbuka"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Custom Meja dan Kursi Besi Minimalis | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"